name: Burpsuite Scan

on:
  push:

jobs:
  Burpsuite-scan:
    name: DAST / Burpsuite
    runs-on: [ self-hosted, Linux, X64 ]
   
    steps:
      - uses: LexisNexis-RBA/bsuk-github-security/.github/actions/burpsuite@nexus-1207-sast-and-dast
        with:
          site-id: ${{ secrets.BURPSUITE_SITEID }}
          api-key: ${{ secrets.BURPSUITE_APIKEY }}
